### ISSUE TITLE
User: Bug report - do we want paystubs uploaded? 

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ssareportchangesletter#14]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `job details`
Steps to reproduce | Letter states "Copies of my pay stubs are
attached." but we do not provide an upload screen or include copy making in the instructions
Expected behavior | -
What happened instead | -
Other information | Form: Report changes to SS
Variable being sought | `jobs[0].employer_type`

**Comment by twhiles** [comment]
this bug will be closed as now out of scope (removing 'dedicated account' portion of code as it is now available directly via the SSA)
