### ISSUE TITLE
User: Bug report - How does office choice work

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ssareportchangesletter#16]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `which office`
Steps to reproduce | Can the user select any office or are they assigned a SS office that should appear on this list? 

If they are assigned an office I'd want to clarify the instructions
Expected behavior | -
What happened instead | -
Other information | Form: Report changes to SS
Variable being sought | `ssa_office.name.text`

**Comment by twhiles** [comment]
this is working in the current interview - will review again in testing.
