### ISSUE TITLE
User: other feedback (covid-related office closings)

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ssareportchangesletter#22]
## User feedback:  
> Change instructions to reflect COVID-related office closings. 

You can mail or fax this letter to your local social security office. To get the address or fax number, call Social Security at 1-800-772-1213 or use the office locator on Social Security's website https://www.ssa.gov/locator/

Take out Deliver your letter in person paragraph.

Question id: `download form`

Variable being sought: `download_form`

**Comment by twhiles** [comment]
@Landon-Shimel - let's either close or update this issue since it was specific to Covid requirements (no longer applicable). We may want to leave open as a placeholder to update the wording (after confirming they will accept anything by mail; I don't see that is a valid option anymore).

**Comment by twhiles** [comment]
not applicable for now (2024 updates - offices are open). separate changes to "next steps" include how to contact the offices.
