### ISSUE TITLE
Re-write the intro screen instructions

### ISSUE THREAD

**Issue by Landon-Shimel** [SuffolkLITLab/docassemble-ssareportchangesletter#40]
Need to re-write this:

"This interview helps a parent or representative payee of a child on SSI keep track of money spent from a dedicated account with the child’s retroactive SSI benefits.

[Learn more about the special rules for dedicated accounts](http://www.gbls.org/sites/default/files/cdp_spending_kit_full.pdf). It’s a good idea to read through the Saving and Spending Workbook before completing this interview.

You can use this interview to fill out a Report of Benefits and Dedicated Account or only to keep track of what you spent.

If you would like to use this interview to keep track of expenses, it’s a good idea to sign up for an account so you can save your work and come back to it."

so it makes better use of plain language, helps the user understand what is being asked of them, and ensures that they are providing correct information.

**Comment by Landon-Shimel** [comment]
Also add in a link to find a lawyer under the “consult a lawyer” text at the bottom of the intro screen

Also Include a list of information for user to gather in order to complete the interview

**Comment by Landon-Shimel** [comment]
Re-write from OpenAI API: 
"This interview is designed to help parents or representatives of children receiving SSI keep track of how money from a dedicated account with the child’s retroactive SSI benefits is spent.

It’s important to familiarize yourself with the special rules for dedicated accounts and review the Saving and Spending Workbook before starting this interview.

You can use this interview to complete a Report of Benefits and Dedicated Account or simply to track expenses.

If you want to keep track of expenses, consider creating an account so you can save your progress and return to it later."

**Comment by twhiles** [comment]
I think it would be a good idea to stop and warn user to review the [Learn more about the special rules for dedicated accounts](http://www.gbls.org/sites/default/files/cdp_spending_kit_full.pdf)" before they are able to proceed. The phrase "learn more" may indicate it isn't required to understand which could lead user to answer items inaccurately.
