### ISSUE TITLE
On the "Events that happened over the last year" screen include options for any of the potential changes that you are required to report, and if any of these are selected, then prompt the interview to include a "report changes to SSI letter" along with the Report of Benefits and Dedicated Account

### ISSUE THREAD

**Issue by Landon-Shimel** [SuffolkLITLab/docassemble-ssareportchangesletter#41]
On the "Did any of the following happen" screen include options for any of the potential changes that you are required to report, and if any of these are selected, then prompt the interview to include a "report changes to SSI letter" along with the Report of Benefits and Dedicated Account

**Comment by twhiles** [comment]
Let's discuss this one - I think it needs to be future tense otherwise user is opening themself up to an overpayment situation if answer incorrectly.
