### ISSUE TITLE
User: Bug report - id: withdrawals - need subsequent question and PDF issue 

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-ssareportchangesletter#8]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `withdrawals`
Steps to reproduce | If a purchase in question in id: withdrawals is not related to one of the three listed categories the PDF requires an explanation
Expected behavior | When I selected "None of the above" or "Something else" for the category of the withdrawal the PDF still check off Yes for 7B even though it should check No. I was never asked to explain how they benefited the beneficiary and so this section was left blank
What happened instead | n/a
Other information | Form:Report of benefits and Dedicated Account
AMS
Variable being sought | `dedicated_account[0].value`

**Comment by stevejaubz** [comment]
`reconsider: True
comment: |
  Make sure all of the withdrawals were used for a valid purpose
code: |
  temp_used_for_valid_purpose = True
  for entry in dedicated_account:
    temp_used_for_valid_purpose &= not set(entry.purpose).isdisjoint(['medical treatment','education','job skills training'])
  used_for_valid_purpose = temp_used_for_valid_purpose`


Remove "set" from isdisjoint and the question is asked after collecting receipts

**Comment by stevejaubz** [comment]
This edit also resolved the checkbox issue on the PDF - it now selects No if the user has selected something else. 

I turned off "None of the above" so the options are :  Medical treatment, education, job skill, something else. 

If we are not prompting the questions regarding food and housing and that should not be added in this category the instructions on  id: benefit should explicitly state that as well as "Something else", add a hint not to include housing and food etc.

**Comment by twhiles** [comment]
Bug issue related to Dedicated Account (out of scope for 'report changes letter' 2023 project)
